// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIzBXlpt3iUT0G0rpCnFmc2NcNAxWyKrc',
    appId: '1:636207317567:web:2584b02c95f3ef0c986e8a',
    messagingSenderId: '636207317567',
    projectId: 'tams-fc4e6',
    authDomain: 'tams-fc4e6.firebaseapp.com',
    storageBucket: 'tams-fc4e6.appspot.com',
    measurementId: 'G-YLW5D2BLK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzZ_fmAEufAvV2Adw5GlIA36Iz-3-bo5w',
    appId: '1:636207317567:android:7baf72312432792c986e8a',
    messagingSenderId: '636207317567',
    projectId: 'tams-fc4e6',
    storageBucket: 'tams-fc4e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBew_ucS6fa2mHUX90q9zaaq3LiBjISjr4',
    appId: '1:636207317567:ios:1c7ae96475f2025a986e8a',
    messagingSenderId: '636207317567',
    projectId: 'tams-fc4e6',
    storageBucket: 'tams-fc4e6.appspot.com',
    iosBundleId: 'com.example.tams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBew_ucS6fa2mHUX90q9zaaq3LiBjISjr4',
    appId: '1:636207317567:ios:1c7ae96475f2025a986e8a',
    messagingSenderId: '636207317567',
    projectId: 'tams-fc4e6',
    storageBucket: 'tams-fc4e6.appspot.com',
    iosBundleId: 'com.example.tams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIzBXlpt3iUT0G0rpCnFmc2NcNAxWyKrc',
    appId: '1:636207317567:web:2ce9aa281db1da3c986e8a',
    messagingSenderId: '636207317567',
    projectId: 'tams-fc4e6',
    authDomain: 'tams-fc4e6.firebaseapp.com',
    storageBucket: 'tams-fc4e6.appspot.com',
    measurementId: 'G-H7ZZ1KMP7J',
  );
}
